# -*- coding: utf-8 -*-
"""lineage_insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZr9-4dIvR3qmTFrcOabayxZRq_VTc_8
"""

import pandas as pd
from collections import defaultdict
import networkx as nx
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

#read csv
df = pd.read_csv("lineage_data.csv")

df['morphology_class'].unique()

roots = df[df['parent_id'] == 0]['track_id'].tolist()
print(f"Root cells: {roots}")

nonRoots = df[df['parent_id'] != 0]['track_id'].tolist()
print(f"non-Root cells: {nonRoots}")

#parent-child(ren) mapping
childrenOf = defaultdict(list)
for _, row in df.iterrows():
  childrenOf[row['parent_id']].append(row['track_id'])

#count children
def count_children(id_):
  total = len(childrenOf[id_])
  for child in childrenOf[id_]:
    total += count_children(child)
  return total

descendantCount = {root: count_children(root) for root in roots}
print(f"Descendants of Root: {descendantCount}")

top5 = sorted(descendantCount.items(), key=lambda x: x[1], reverse=True)[:5]

for root, size in top5:
  print(f"Root {root} --> {size} descendants")

#all cells in lineage
def get_lineage(rootId, children):
  lineage = set()
  stack = [rootId]
  while stack:
    node = stack.pop()
    lineage.add(node)
    stack.extend(childrenOf[node])
  return lineage

from re import sub
top5_lineages = []

for root, _ in top5:
  lineage_cells = get_lineage(root, childrenOf)
  sub_df = df[df['track_id'].isin(lineage_cells)].copy()
  top5_lineages.append((root, sub_df))

#VISUALIZATION
morph_colors = {
    'Divided': 'green',
    'Elongated': 'blue',
    'None': 'gray'  # for missing morphology
}

for _, sub_df in top5_lineages:
    sub_df['color'] = sub_df['morphology_class'].map(morph_colors).fillna('gray')

def hierarchy_pos(G, root=None, width=1., vert_gap=0.2, vert_loc=0, xcenter=0.5):
    pos = {}
    def _hierarchy_pos(G, root, left, right, vert_loc):
        children = list(G.successors(root))
        pos[root] = ((left+right)/2., vert_loc)
        if children:
            dx = (right - left) / len(children)
            for i, child in enumerate(children):
                _hierarchy_pos(G, child, left + i*dx, left + (i+1)*dx, vert_loc-vert_gap)
    _hierarchy_pos(G, root, 0, width, vert_loc)
    return pos

fig, axes = plt.subplots(1, len(top5_lineages), figsize=(25, 6))

for ax, (root, sub_df) in zip(axes, top5_lineages):
    G = nx.DiGraph()
    for _, row in sub_df.iterrows():
        if row['parent_id'] != 0:
            G.add_edge(row['parent_id'], row['track_id'])

    pos = hierarchy_pos(G, root=root)

    node_colors = [
        morph_colors.get(row, 'gray')
        for row in sub_df.set_index('track_id')['morphology_class'].reindex(G.nodes()).fillna('None/Other')
    ]

    nx.draw(G, pos=pos, with_labels=True, node_color=node_colors,
            node_size=500, arrowsize=15, edge_color='lightgray', ax=ax)
    ax.set_title(f'Root {root}', fontsize=12)

# shared legend for the whole figure
legend_elements = [Patch(facecolor=color, label=morph) for morph, color in morph_colors.items()]
fig.legend(handles=legend_elements, title="Morphology", loc='upper center', ncol=len(morph_colors), fontsize=10)

plt.tight_layout(rect=[0, 0, 1, 0.9])  # Leave space on top for legend
plt.show()

#STATISTICS
df['lifespan'] = df['end_frame'] - df['start_frame']
df['lifespan']

lifespan_stats = df['lifespan'].describe()
print("Lifespan statistics:")
print(f"Total no. of cells (for which lifespan was calculated:  {lifespan_stats.count()}")
print(f"Avg lifespan of all cells: \t\t\t\t{lifespan_stats.mean():.2f}")
print(f"Standard Deviation: \t\t\t\t\t{lifespan_stats.std():.2f}")
print(f"Shortest lived cell: \t\t\t\t\t{lifespan_stats.min()}")
print(f"Longest lived cell: \t\t\t\t\t{lifespan_stats.max()}")

#avg_lifespan_per_lineage
print("\nAvg lifespans per lineage")
for root, sub_df in top5_lineages:
  sub_df['lifespan'] = sub_df['end_frame'] - sub_df['start_frame']
  print(f"Root id {root}: {sub_df['lifespan'].mean():.2f} frames")


divisions = df[df['morphology_class'] == "Divided"].shape[0]
total_cells = df.shape[0]
div_freq = divisions / total_cells
print(f"Total Divisions: {divisions}")
print(f"Total cells: {total_cells}")
print(f"\nDivision Frequency: {div_freq:.2f}")


morph_dist = df['morphology_class'].value_counts()
morph_dist_per = df['morphology_class'].value_counts(normalize=True) * 100

print("Morphology counts:")
print(f"Divided:   {morph_dist.Divided}")
print(f"Elongated: {morph_dist.Elongated}")
print("\nMorphology percentages:")
print(f"Divided:   {morph_dist_per.Divided:.2f}")
print(f"Elongated: {morph_dist_per.Elongated:.2f}")

